# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-StackTrace
version:      1.04
version_from: StackTrace.pm
installdirs:  site
requires:
    Test::More:                    0.46

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
