--- #YAML:1.0
name: Devel-StackTrace
version: 1.08
author:
  - Dave Rolsky, <autarch@urth.org>
abstract: Stack trace and stack trace frame objects
license: perl
requires:
  Test::More: 0.46
provides:
  Devel::StackTrace:
    file: lib/Devel/StackTrace.pm
    version: 1.08
  Devel::StackTraceFrame:
    file: lib/Devel/StackTrace.pm
    version: 1.08
generated_by: Module::Build version 0.23
