---
name: Devel-StackTrace
version: 1.15
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Stack trace and stack trace frame objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0
  Test::More: 0.46
provides:
  Devel::StackTrace:
    file: lib/Devel/StackTrace.pm
    version: 1.15
  Devel::StackTraceFrame:
    file: lib/Devel/StackTrace.pm
    version: 0.6
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
